version: '3.7'

services:
  database:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
